# Base CUDA image with Python 3.10
FROM nvidia/cuda:11.8.0-cudnn8-runtime-ubuntu20.04

# Install necessary packages including Python
RUN apt-get update && apt-get install -y python3-pip

# Set working directory
WORKDIR /app

# Copy requirements and install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the application code
COPY . .

# Expose port 8000 for the Django server
EXPOSE 8000

# Set environment variables for model paths and device
ENV MODEL_DIRECTORY_PATH=/app/model
ENV ADAPTER_PATH=/app/adapter
ENV DEVICE=cuda:2

# Run Django server using Gunicorn
CMD ["gunicorn", "autograding_project.wsgi:application", "--bind", "0.0.0.0:8000", "--timeout", "300"]
