# Base image
FROM python:3.10-slim

# Set working directory
WORKDIR /app

# Copy requirements and install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the application code
COPY . .

# Expose port 8501 for Streamlit
EXPOSE 8501

# Run Streamlit server
CMD ["streamlit", "run", "grading_interface.py", "--server.fileWatcherType=none", "--server.enableCORS=false", "--server.enableXsrfProtection=false"]
# streamlit run grading_interface.py --server.fileWatcherType=none